### ISSUE TITLE
pip install pyro-ppl failing in Python 3

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/pyro#1759]
```
$ conda create -n test3 python=3
...
$ source activate test3
$ pip install pyro-ppl
Collecting pyro-ppl
  Downloading https://files.pythonhosted.org/packages/75/0e/e6013ad748349e447c6da7ba0b3d66950e834a5b45a0ff426c131b00cde5/pyro-ppl-0.3.1.tar.gz (207kB)
    100% |████████████████████████████████| 215kB 4.9MB/s
    Complete output from command python setup.py egg_info:
    fatal: Not a git repository (or any of the parent directories): .git
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/c5/cqn89jt900v5tmm2y7p0tf4r0000gn/T/pip-install-6feboagj/pyro-ppl/setup.py", line 25, in <module>
        cwd=PROJECT_PATH).decode('ascii').strip()
      File "/Users/fritzobermeyer/miniconda2/envs/test3/lib/python3.7/subprocess.py", line 395, in check_output
        **kwargs).stdout
      File "/Users/fritzobermeyer/miniconda2/envs/test3/lib/python3.7/subprocess.py", line 487, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['git', 'tag', '--points-at', 'HEAD']' returned non-zero exit status 128.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/c5/cqn89jt900v5tmm2y7p0tf4r0000gn/T/pip-install-6feboagj/pyro-ppl/
```

**Comment by fritzo** [comment]
Seems to be fixed by our 0.3.1.post1 release.
