### ISSUE TITLE
[bug] Bayesian Linear Regression random_module IndexError

### ISSUE THREAD

**Issue by jmamath** [pyro-ppl/pyro#1924]
### Issue Description
I am following the tutorial on Bayesian Linear Regression (part I), and it seems that the random_module function doesn't sample correct models. The only difference with the tutorial is that I removed the factor for simplicity, and I used 3 features, as this is the dimension of the input space x_data.

### Environment
For any bugs, please provide the following:
MacOS Sierra
python                    3.7.3                h359304d_0  
pytorch                   1.1.0                   py3.7_0    pytorch
pyro-ppl                  0.3.3                    pypi_0    pypi

### Code Snippet
Here is the simple regression class. I remove factor for the sake of simplicity
```
class RegressionModel(nn.Module):
    def __init__(self, p):
        # p = number of features
        super(RegressionModel, self).__init__()
        self.linear = nn.Linear(p, 1)

    def forward(self, x):
        return self.linear(x) 
p = 3  # number of features
regression_model = RegressionModel(p)
```
I used the same data as in the tutorial and I have been able to train`regression_model` 
Here is the model now

```
w_prior = Normal(torch.zeros(3), torch.ones(3)).to_event(1)
b_prior = Normal(torch.Tensor([8.]), torch.Tensor([1000.])).to_event(1)
priors = {'linear.weight': w_prior, 'linear.bias': b_prior}
scale = pyro.sample("sigma", Uniform(0., 10.))
# lift module parameters to random variables sampled from the priors
lifted_module = pyro.random_module("module", regression_model, priors)
lifted_reg_model = lifted_module()

lifted_reg_model(x_data)
```
Then I get the following error
```

Traceback (most recent call last):

  File "<ipython-input-28-7c1fb88efcaa>", line 1, in <module>
    lifted_reg_model(x_data)

  File "/var/root/anaconda3/envs/Pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)

  File "<ipython-input-1-80d74cc90af8>", line 61, in forward
    return self.linear(x)

  File "/var/root/anaconda3/envs/Pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)

  File "/var/root/anaconda3/envs/Pytorch/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 92, in forward
    return F.linear(input, self.weight, self.bias)

  File "/var/root/anaconda3/envs/Pytorch/lib/python3.7/site-packages/torch/nn/functional.py", line 1406, in linear
    ret = torch.addmm(bias, input, weight.t())

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)


```

**Comment by eb8680** [comment]
Looks like your `weight` prior is missing a dimension - `nn.Linear` expects its weights to be 2-dimensional and `w_prior.sample().shape == (3,)`

**Comment by jmamath** [comment]
Yes, it worked. Thank you.
