### ISSUE TITLE
vae.py tutorial is broken

### ISSUE THREAD

**Issue by mattphillipsphd** [pyro-ppl/pyro#2037]
### Issue Description

The `__init__` function of `class MNISTCached` uses the `data` and `targets` attributes before they have been initialized.  I tried a little code reorganization to get it to work but that wasn't sufficient to fix it.  

### Environment
For any bugs, please provide the following:
 - OS and python version: Ubuntu 18.04, Python 3.6.3
 - PyTorch version: 1.0.0
 - Pyro version: 0.4.1

### Code Snippet
Provide any relevant code snippets and commands run to replicate the issue.

```
(torch100) matt@mattp-7920: $ python pyro_vae.py
Traceback (most recent call last):
  File "pyro_vae.py", line 213, in <module>
    model = main(args)
  File "pyro_vae.py", line 124, in main
    train_loader, test_loader = setup_data_loaders(MNIST, use_cuda=args.cuda, batch_size=256)
  File "/home/matt/Repos/lifeomic/ehr_clean/trainers/pyro_utils/mnist_cached.py", line 221, in setup_data_loaders
    sup_num=sup_num, use_cuda=use_cuda)
  File "/home/matt/Repos/lifeomic/ehr_clean/trainers/pyro_utils/mnist_cached.py", line 149, in __init__
    self.data = (transform(self.data.float()))
AttributeError: 'MNISTCached' object has no attribute 'data'
```

The code: 
```
      # pyro-ppl/pyro/examples/vae/utils/mnist_cached.py

        if mode in ["sup", "unsup", "valid"]:                                    
                                                                                 
            # transform the training data if transformations are provided        
            if transform is not None:                                            
                self.data = (transform(self.data.float()))                       
            if target_transform is not None:                                     
                self.targets = (target_transform(self.targets))                  
                                                                                 
            if MNISTCached.train_data_sup is None:                               
                if sup_num is None:                                              
                    assert mode == "unsup"                                       
                    MNISTCached.train_data_unsup, MNISTCached.train_labels_unsup = \
                        self.data, self.targets                                  
                else:                                                            
                    MNISTCached.train_data_sup, MNISTCached.train_labels_sup, \  
                        MNISTCached.train_data_unsup, MNISTCached.train_labels_unsup, \
                        MNISTCached.data_valid, MNISTCached.labels_valid = \     
                        split_sup_unsup_valid(self.data, self.targets, sup_num)  
                                                                                 
            if mode == "sup":                                                    
                self.data, self.targets = MNISTCached.train_data_sup, MNISTCached.train_labels_sup
            elif mode == "unsup":                                                
                self.data = MNISTCached.train_data_unsup                         
                                                                                 
                # making sure that the unsupervised labels are not available to inference
                self.targets = (torch.Tensor(                                    
                    MNISTCached.train_labels_unsup.shape[0]).view(-1, 1)) * np.nan
            else:                                                                
                self.data, self.targets = MNISTCached.data_valid, MNISTCached.labels_valid
```

**Comment by neerajprad** [comment]
Could you try using the latest pytorch version - 1.2 and check if that works?

**Comment by jpchen** [comment]
IIRC this was the torchvision issue, @mattphillipsphd what version are you using? you probably need to downgrade your version.

**Comment by mattphillipsphd** [comment]
Thanks both @neerajprad and @jpchen , indeed upgrading to pytorch 1.2.0 solved this issue.  The model is training now.
