### ISSUE TITLE
VAE example fails validation

### ISSUE THREAD

**Issue by nasosev** [pyro-ppl/pyro#2038]
### Issue Description
Vae.py example fails validation if the command `pyro.enable_validation(True)` is included.

### Environment
 - Win10, Python 3.7.3
 - PyTorch version: 1.2.0
 - Pyro version: 0.4.1

### Code Snippet
Stack trace:

```
Traceback (most recent call last):
  File "C:\Users\nasos\Miniconda3\lib\site-packages\pyro\poutine\trace_struct.py", line 213, in compute_log_prob
    log_p = site["fn"].log_prob(site["value"], *site["args"], **site["kwargs"])
  File "C:\Users\nasos\Miniconda3\lib\site-packages\torch\distributions\independent.py", line 88, in log_prob
    log_prob = self.base_dist.log_prob(value)
  File "C:\Users\nasos\Miniconda3\lib\site-packages\torch\distributions\bernoulli.py", line 93, in log_prob
    self._validate_sample(value)
  File "C:\Users\nasos\Miniconda3\lib\site-packages\torch\distributions\distribution.py", line 253, in _validate_sample
    raise ValueError('The value argument must be within the support')
ValueError: The value argument must be within the support

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "vae.py", line 214, in <module>
    model = main(args)
  File "vae.py", line 155, in main
    epoch_loss += svi.step(x)
  File "C:\Users\nasos\Miniconda3\lib\site-packages\pyro\infer\svi.py", line 98, in step
    loss = self.loss_and_grads(self.model, self.guide, *args, **kwargs)
  File "C:\Users\nasos\Miniconda3\lib\site-packages\pyro\infer\trace_elbo.py", line 123, in loss_and_grads
    for model_trace, guide_trace in self._get_traces(model, guide, *args, **kwargs):
  File "C:\Users\nasos\Miniconda3\lib\site-packages\pyro\infer\elbo.py", line 167, in _get_traces
    yield self._get_trace(model, guide, *args, **kwargs)
  File "C:\Users\nasos\Miniconda3\lib\site-packages\pyro\infer\trace_elbo.py", line 50, in _get_trace
    "flat", self.max_plate_nesting, model, guide, *args, **kwargs)
  File "C:\Users\nasos\Miniconda3\lib\site-packages\pyro\infer\enum.py", line 49, in get_importance_trace
    model_trace.compute_log_prob()
  File "C:\Users\nasos\Miniconda3\lib\site-packages\pyro\poutine\trace_struct.py", line 218, in compute_log_prob
    .format(name, exc_value, shapes)).with_traceback(traceback)
  File "C:\Users\nasos\Miniconda3\lib\site-packages\pyro\poutine\trace_struct.py", line 213, in compute_log_prob
    log_p = site["fn"].log_prob(site["value"], *site["args"], **site["kwargs"])
  File "C:\Users\nasos\Miniconda3\lib\site-packages\torch\distributions\independent.py", line 88, in log_prob
    log_prob = self.base_dist.log_prob(value)
  File "C:\Users\nasos\Miniconda3\lib\site-packages\torch\distributions\bernoulli.py", line 93, in log_prob
    self._validate_sample(value)
  File "C:\Users\nasos\Miniconda3\lib\site-packages\torch\distributions\distribution.py", line 253, in _validate_sample
    raise ValueError('The value argument must be within the support')
ValueError: Error while computing log_prob at site 'obs':
The value argument must be within the support
        Trace Shapes:            
         Param Sites:            
 decoder$$$fc1.weight 400  50    
   decoder$$$fc1.bias     400    
decoder$$$fc21.weight 784 400    
  decoder$$$fc21.bias     784    
        Sample Sites:            
          latent dist 256   |  50
                value 256   |  50
             log_prob 256   |    
             obs dist 256   | 784
                value 256   | 784
```

**Comment by neerajprad** [comment]
I think this is just related to the fact that our observed values are continuous in the interval `(0, 1)` and hence declared invalid as samples from a Bernoulli distribution when distributions arg validation is enabled. However, `Bernoulli.log_prob` is able to score the samples just fine using binary cross entropy which is what a lot of the literature does too if you were to write the loss directly without using any distributions. Refer to https://github.com/pyro-ppl/pyro/issues/529 for more details. Feel free to reopen that issue if you have an alternative suggestion.
