### ISSUE TITLE
Progressbar Bug with tqdm v4.36.1 and Pyro v0.4.1 leading to exception, displaying progress for multiple chains

### ISSUE THREAD

**Issue by NarayanSchuetz** [pyro-ppl/pyro#2091]
The latest tqdm version 4.36.1 raises an exception when it should display multiple progress bars, such that:

```
init_params, potential_fn, transforms, _ = initialize_model(model_label_uncertainty, model_args=(X_train_t, y_train_t),
                                                                num_chains=3)
nuts_kernel = NUTS(potential_fn=potential_fn)
mcmc = MCMC(nuts_kernel,
            num_samples=2000,
            warmup_steps=500,
            num_chains=3,
            initial_params=init_params,
            transforms=transforms)
```
results in:
```
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/home/test/anaconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/test/anaconda3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/test/anaconda3/lib/python3.7/site-packages/pyro/infer/mcmc/api.py", line 34, in logger_thread
    progress_bars = ProgressBar(warmup_steps, num_samples, disable=disable_progbar, num_bars=num_chains)
  File "/home/test/anaconda3/lib/python3.7/site-packages/pyro/infer/mcmc/logger.py", line 69, in __init__
    position=i, file=sys.stderr, disable=disable)
  File "/home/test/anaconda3/lib/python3.7/site-packages/tqdm/notebook.py", line 201, in __init__
    kwargs['bar_format'] = kwargs['bar_format'].replace('{bar}', '<bar/>')
AttributeError: 'NoneType' object has no attribute 'replace'

Exception ignored in: <function tqdm.__del__ at 0x7fb11d94d598>
Traceback (most recent call last):
  File "/home/test/anaconda3/lib/python3.7/site-packages/tqdm/std.py", line 1039, in __del__
    self.close()
  File "/home/test/anaconda3/lib/python3.7/site-packages/tqdm/notebook.py", line 240, in close
    super(tqdm_notebook, self).close(*args, **kwargs)
  File "/home/test/anaconda3/lib/python3.7/site-packages/tqdm/std.py", line 1215, in close
    if self.disable:
AttributeError: 'tqdm_notebook' object has no attribute 'disable'
```

Did not look deeply but might be caused as a result of [tqdm_notebook](https://github.com/tqdm/tqdm/blob/91494ccf363e5eeb4745db7dbab70ef73c4a6eb0/tqdm/notebook.py#L200) expecting `bar_format` kwargs value to be either missing (thus the key not present in the dict, in which case it is set to default) or a valid value but not `None`, which seems to be a valid program state in Pyro.

**Comment by fehiepsi** [comment]
Hi @NarayanSchuetz, thank you so much for reporting the issue and helping us isolate the issue! We incorporated the fix in #2089, which will be available soon in 0.5.2 version.

**Comment by neerajprad** [comment]
@NarayanSchuetz, @fehiepsi - this is 0.5.1 release; and it should be available now for pip install.

**Comment by fehiepsi** [comment]
> this is 0.5.1 release

Opps... I got confused with funsor version. Thanks for correcting me, Neeraj!
