### ISSUE TITLE
Several iterations into NUTS, sampling from a Categorical distribution unexpectedly returns multiple values

### ISSUE THREAD

**Issue by m-k-S** [pyro-ppl/pyro#2159]
### Issue Description

While attempting to perform inference on a model (code located below) using NUTS/MCMC, after several (~100) iterations, I get the error: `ValueError: only one element tensors can be converted to Python scalars`. When adding a print statement to relevant variable, which is a draw from a Categorical distribution, it became clear that the variable was now a two-element tensor, hence the issue. However, I don't see why a draw from a Categorical distribution should be returning a two element tensor.

### Environment

I am running this in Google Colab, using Python 3.6, pyro-ppl-0.5.1, torch 1.3.0.

### Code Snippet

<details>

```
import torch
import pyro.distributions as dist
import pyro
from pyro.infer import NUTS, MCMC
from torch.distributions import constraints
from pyro import poutine

data1 = dist.MultivariateNormal(-5 * torch.ones(2), torch.eye(2)).sample([100])
data2 = dist.MultivariateNormal(5 * torch.ones(2), torch.eye(2)).sample([100])
data = torch.cat((data1, data2))

pyro.enable_validation(True)

N = len(data)
T = 2

def mix_weights(beta): 
    weights = torch.zeros(beta.shape[0] + 1)
    for t in range(beta.shape[0]):
      weights[t] = beta[t] * torch.prod(1. - beta[:t], dim=0)
    weights[beta.shape[0]] = 1. - torch.sum(weights)
    return weights

def model(data):
    alpha = 1.2
    with pyro.plate("beta_plate", T-1):
      beta = pyro.sample("beta", dist.Beta(1, alpha))

    with pyro.plate("mu_plate", T):
      mu = pyro.sample("mu", dist.MultivariateNormal(torch.zeros(2), 5 * torch.eye(2)))

    for i in range(N):
      z = pyro.sample("z_{}".format(i), dist.Categorical(mix_weights(beta)))
      print (z.numpy())
      pyro.sample("obs_{}".format(i), dist.MultivariateNormal(mu[z.item()], torch.eye(2)), obs=data[i])

nuts_kernel = NUTS(model, adapt_step_size=True)
mcmc = MCMC(nuts_kernel, num_samples=500, warmup_steps=300)
mcmc.run(data)

samples = mcmc.get_samples()
print(samples)
```
</details>

Output:

<details>

```
Warmup:   0%|          | 0/800 [00:00, ?it/s]0
0
0
0
0
0
1
1
0
1
0
1
0
0
1
0
1
0
0
0
0
0
0
0
0
0
0
1
0
0
1
0
1
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
1
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
1
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
1
0
0
1
0
0
0
0
0
1
0
0
0
1
0
1
1
0
1
0
0
0
1
0
0
0
0
0
1
0
0
0
0
0
0
1
1
0
0
0
0
0
0
0
1
1
0
1
0
0
0
0
0
0
0
0
0
1
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
[[0]
 [1]]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/pyro/poutine/trace_messenger.py in __call__(self, *args, **kwargs)
    142             try:
--> 143                 ret = self.fn(*args, **kwargs)
    144             except (ValueError, RuntimeError):

16 frames
ValueError: only one element tensors can be converted to Python scalars

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-19-63983afdb4c3> in model(data)
     22       z = pyro.sample("z_{}".format(i), dist.Categorical(mix_weights(beta)))
     23       print (z.numpy())
---> 24       pyro.sample("obs_{}".format(i), dist.MultivariateNormal(mu[z.item()], torch.eye(2)), obs=data[i])
     25 
     26 nuts_kernel = NUTS(model, adapt_step_size=True)

ValueError: only one element tensors can be converted to Python scalars
  Trace Shapes:        
   Param Sites:        
  Sample Sites:        
beta_plate dist     |  
          value   1 |  
      beta dist   1 |  
          value   1 |  
  mu_plate dist     |  
          value   2 |  
        mu dist   2 | 2
          value   2 | 2
       z_0 dist     |  
          value 2 1 |  
```

</details>

**Comment by fehiepsi** [comment]
@m-k-S In Pyro, NUTS marginalizes discrete latent variable, so you should use `mu[z]` in place of `mu[z.item()`. However, you will need more batteries to [enumerate more than 25 variables](http://pyro.ai/examples/enumeration.html#How-to-enumerate-more-than-25-variables). For your model, I think that using
```
    with pyro.plate("data", N):
        z = pyro.sample("z", dist.Categorical(weights))
        pyro.sample("obs", dist.MultivariateNormal(mu[z], torch.eye(2)), obs=data)
```
is enough.

**Comment by fritzo** [comment]
@fehiepsi do I understand correctly that the first few scalar samples were drawn during NUTS initialization, not during NUTS iteration, and that in fact the non-scalar site is encountered on the first NUTS step?

**Comment by fehiepsi** [comment]
@fritzo Yes, scalar samples are drawn during inspecting the model to detect its structure. After that, [enumerate will be activated](https://github.com/pyro-ppl/pyro/blob/dev/pyro/infer/mcmc/util.py#L368) by wrapping the model with `poutine.enum`. Non-scalar site is encountered at the initialization phase too.

**Comment by m-k-S** [comment]
Thanks @fehiepsi, this worked perfectly.

**Comment by jmugan** [comment]
I have the same problem, but I don't understand this conversation. So, once enumeration starts, you have to do more complex stuff as described here http://pyro.ai/examples/enumeration.html? Is there like a `just-do-simple-thing-i-dont-care-if-it-is-slower` flag I can pass?

**Comment by fehiepsi** [comment]
@jmugan If your model does not have continuous latent variables, MCMC will collect nothing. Could you create a separate issue if that is not the case?

**Comment by jmugan** [comment]
It does have continuous variables as well. I'll create a small example program to illustrate the problem and open a separate issue. Thanks!

**Comment by RylanSchaeffer** [comment]
Hi all! I have a related-but-not-quite-identical issue. I'm trying to use NUTS to sample from a Dirichlet Process Mixture of Gaussians by modifying the Pyro example (https://pyro.ai/examples/dirichlet_process_mixture.html). However, I'm getting the error:

```
Warmup:   0%|          | 0/20300 [00:00, ?it/s]Traceback (most recent call last):
  File "/home/rylan/.local/lib/python3.6/site-packages/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/rylan/.local/lib/python3.6/site-packages/pyro/infer/mcmc/api.py", line 380, in run
    for x, chain_id in self.sampler.run(*args, **kwargs):
  File "/home/rylan/.local/lib/python3.6/site-packages/pyro/infer/mcmc/api.py", line 169, in run
    *args, **kwargs):
  File "/home/rylan/.local/lib/python3.6/site-packages/pyro/infer/mcmc/api.py", line 111, in _gen_samples
    kernel.setup(warmup_steps, *args, **kwargs)
  File "/home/rylan/.local/lib/python3.6/site-packages/pyro/infer/mcmc/hmc.py", line 303, in setup
    self._initialize_model_properties(args, kwargs)
  File "/home/rylan/.local/lib/python3.6/site-packages/pyro/infer/mcmc/hmc.py", line 255, in _initialize_model_properties
    initial_params=self._initial_params,
  File "/home/rylan/.local/lib/python3.6/site-packages/pyro/infer/mcmc/util.py", line 409, in initialize_model
    max_plate_nesting)
  File "/home/rylan/.local/lib/python3.6/site-packages/pyro/infer/mcmc/util.py", line 176, in __init__
    self._populate_cache(model_trace)
  File "/home/rylan/.local/lib/python3.6/site-packages/pyro/infer/mcmc/util.py", line 188, in _populate_cache
    model_trace.compute_log_prob()
  File "/home/rylan/.local/lib/python3.6/site-packages/pyro/poutine/trace_struct.py", line 216, in compute_log_prob
    log_p = site["fn"].log_prob(site["value"], *site["args"], **site["kwargs"])
  File "/usr/local/lib/python3.6/dist-packages/torch/distributions/multivariate_normal.py", line 208, in log_prob
    M = _batch_mahalanobis(self._unbroadcasted_scale_tril, diff)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributions/multivariate_normal.py", line 57, in _batch_mahalanobis
    M_swap = torch.triangular_solve(flat_x_swap, flat_L, upper=False)[0].pow(2).sum(-2)  # shape = b x c
RuntimeError: expected scalar type Double but found Float
```

My code is copied below:

```
    def mix_weights(beta):
        beta1m_cumprod = (1 - beta).cumprod(-1)
        return F.pad(beta, (0, 1), value=1) * F.pad(beta1m_cumprod, (1, 0), value=1)

    def model(data):
        with pyro.plate('beta_plate', sampling_max_num_clusters - 1):
            beta = pyro.sample(
                'beta',
                pyro.distributions.Beta(1, alpha))

        with pyro.plate('mean_plate', sampling_max_num_clusters):
            mean = pyro.sample(
                'mean',
                pyro.distributions.MultivariateNormal(torch.zeros(obs_dim),
                                                      torch.eye(obs_dim)))

        with pyro.plate('data', num_obs):
            z = pyro.sample(
                'z',
                pyro.distributions.Categorical(mix_weights(beta=beta)))
            pyro.sample(
                'obs',
                pyro.distributions.MultivariateNormal(
                    mean[z],
                    torch.eye(obs_dim)),
                obs=torch_observations)

    nuts_kernel = pyro.infer.NUTS(model=model, adapt_step_size=True)
    mcmc = pyro.infer.MCMC(
        kernel=nuts_kernel,
        num_samples=num_samples,
        warmup_steps=300)
    mcmc.run(torch_observations)
```

**Comment by RylanSchaeffer** [comment]
Does anyone know where this apparent precision error is originating from?

**Comment by martinjankowiak** [comment]
you probably need to make changes like `torch.eye(obs_dim, dtype=z.dtype, device=z.device)`
with similar changes for `torch.ones` etc.

you can also try things like 
torch.set_default_tensor_type('torch.FloatTensor')

**Comment by RylanSchaeffer** [comment]
Setting the default tensor type appears to have done the trick! Thank you @martinjankowiak !

**Comment by RylanSchaeffer** [comment]
@fehiepsi , is there a way to prevent NUTS from marginalizing discrete variables?

**Comment by fehiepsi** [comment]
I think you can do `x = sample('x', d.mask(False), obs=...)`, or simply `x = ...` where `...` is a fixed value of `x`.

**Comment by RylanSchaeffer** [comment]
What is `d`? The discrete variable? When I try that, I get an attribute error: `'Tensor' object has no attribute 'mask'`

```
            pyro.sample(
                'obs',
                pyro.distributions.MultivariateNormal(
                    mean[z].mask(False),
                    torch_gaussian_cov_scaling * torch.eye(obs_dim)),
                obs=obs)
```

**Comment by fehiepsi** [comment]
Sorry, with your code, it will be
```
z = pyro.sample(
                'z',
                pyro.distributions.Categorical(mix_weights(beta=beta)).mask(False), obs=...)
```
or simply
```
z = ...
```

**Comment by RylanSchaeffer** [comment]
When I try that, no errors are raised, but `mcmc.get_samples()` doesn't return any sampled discrete variables.

**Comment by RylanSchaeffer** [comment]
The returned dict has only samples for `beta` (the stick breaking variables)  and `mean` (the Gaussian means).

**Comment by RylanSchaeffer** [comment]
Code:
```
    def mix_weights(beta):
        beta1m_cumprod = (1 - beta).cumprod(-1)
        return F.pad(beta, (0, 1), value=1) * F.pad(beta1m_cumprod, (1, 0), value=1)

    def model(obs):
        with pyro.plate('beta_plate', sampling_max_num_clusters - 1):
            beta = pyro.sample(
                'beta',
                pyro.distributions.Beta(1, torch_alpha))

        with pyro.plate('mean_plate', sampling_max_num_clusters):
            mean = pyro.sample(
                'mean',
                pyro.distributions.MultivariateNormal(
                    torch.zeros(obs_dim),
                    torch_gaussian_mean_prior_cov_scaling * torch.eye(obs_dim)))

        with pyro.plate('data', num_obs):
            z = pyro.sample(
                'z',
                pyro.distributions.Categorical(mix_weights(beta=beta)).mask(False))
            pyro.sample(
                'obs',
                pyro.distributions.MultivariateNormal(
                    mean[z],
                    torch_gaussian_cov_scaling * torch.eye(obs_dim)),
                obs=obs)

    # serving_model = pyro.infer.infer_discrete(model, first_available_dim=-1)
    nuts_kernel = pyro.infer.NUTS(model=model, adapt_step_size=True)
    mcmc = pyro.infer.MCMC(
        kernel=nuts_kernel,
        num_samples=num_samples,
        warmup_steps=3)
    mcmc.run(torch_observations)
    samples = mcmc.get_samples()

```

**Comment by fehiepsi** [comment]
I see. If you want to run MCMC over those discrete latent variables (without marginalization), it is better to use [HMCGibbs](http://num.pyro.ai/en/stable/mcmc.html#numpyro.infer.hmc_gibbs.HMCGibbs) in NumPyro. Currently, we don't have support HMC within Gibbs in Pyro.

**Comment by RylanSchaeffer** [comment]
Ok thank you.
