### ISSUE TITLE
Planar Transform output dimension of log_abs_det_jacobian incorrect

### ISSUE THREAD

**Issue by vikigenius** [pyro-ppl/pyro#2423]
Here is the code to reproduce the issue

```
import torch
from pyro.distributions import Normal
from pyro.distributions.transforms import CatTransform, Planar


prior = Normal(torch.zeros(4, 8), torch.ones(4, 8)).independent(1)
t1 = Planar(4)
t2 = Planar(4)
t = CatTransform([t1, t2], dim=1, lengths=[4, 4])
ps = prior.sample()
tps = t(ps)
l = t.log_abs_det_jacobian(ps, tps) # This line throws an error:

Traceback (most recent call last):
  File "pyro_bug.py", line 14, in <module>
    l = t.log_abs_det_jacobian(ps, tps)
  File "/home/void/.miniconda3/envs/allennlp/lib/python3.7/site-packages/torch/distributions/transforms.py", line 615, in log_abs_det_jacobian
    return torch.cat(logdetjacs, dim=self.dim)
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

```

This seems to be happening because the log_abs_det_jacobian returned by planar is of size ([4]) and not size([4, 1]). I am not sure if this should be fixed in Planar or if it should be fixed in CatTransform, but this does seem to be a problem?

**Comment by fritzo** [comment]
cc @stefanwebb

**Comment by stefanwebb** [comment]
Hi @vikigenius, thanks for submitting this issue! The `.log_abs_det_jacobian` of `Planar` returns size `([4])` in this case because it has `event_size=1`: it defines a multivariate distribution over vectors. If it were an element-wise transform like say `SigmoidTransform` if would return size `([4,1])`.

The bug is in `CatTransform`, which only seems designed for element-wise transforms, those with `event_size=0`. Let me think about how to fix this and I'll post a PR here or in PyTorch soon

**Comment by stefanwebb** [comment]
See https://github.com/pytorch/pytorch/pull/36878
