### ISSUE TITLE
Sampling Categorical Quits After Two Samples [bug, but probably user error]

### ISSUE THREAD

**Issue by jmugan** [pyro-ppl/pyro#2607]
### Issue Description
The sampler works with a Gaussian but not with categorical. Similar as https://github.com/pyro-ppl/pyro/issues/2159 but it was suggested that I open a new issue.

### Environment
Python 3.7 with Pyro 1.4.0

### Code Snippet
If I set `use_gaussian` to True it works as expected.

```
import torch
import pyro
import pyro.distributions as dist
import pyro.poutine as poutine
from pyro.infer import MCMC, NUTS
#pyro.set_rng_seed(101)

# This works if I set it to True
use_gaussian = False

def model(prior_elves):
    print('prior:', prior_elves)
    if use_gaussian:
        num_elves = pyro.sample("num_elves",
                                   dist.Normal(prior_elves, torch.tensor(2.0)))
    else:
        num_elves = pyro.sample("num_elves",
                               pyro.distributions.Categorical(probs=prior_elves))
    print("Num elves: ", num_elves)

    num_rocks = num_elves * 4
    num_logs = num_elves * 6

    print(f"Rocks: {num_rocks}, Logs: {num_logs}")

    # begin https://pyro.ai/examples/intro_part_ii.html

    rocks_observed = pyro.sample("rocks_observed",
                                   dist.Normal(num_rocks, torch.tensor(3.0)))

    logs_observed = pyro.sample("logs_observed",
                                   dist.Normal(num_logs, torch.tensor(3.0)))

    print(f"Rocks obs: {rocks_observed}, Logs obs: {logs_observed}")

    return num_elves

def conditioned_model(model, data, prior_elves):
    return poutine.condition(model, data=data)(prior_elves)

data = {"rocks_observed": torch.tensor(4),
    "logs_observed": torch.tensor(6),
    }

if use_gaussian:
    prior_elves = torch.tensor(2.0)
else:
    prior_elves = torch.tensor([.2,.2,.2,.2,.2])

nuts_kernel = NUTS(conditioned_model, jit_compile=False)
mcmc = MCMC(nuts_kernel,
                num_samples=10,
                warmup_steps=5,
                num_chains=1)
mcmc.run(model, data, prior_elves)

mcmc.summary(prob=.5)
```

Gives the output
```
Sample: 100%|██████████| 15/15 [00:00, 1853.70it/s, step size=1.00e+00, acc. prob=1.000]
prior: tensor([0.2000, 0.2000, 0.2000, 0.2000, 0.2000])
Num elves:  tensor(4)
Rocks: 16, Logs: 24
Rocks obs: 4, Logs obs: 6
prior: tensor([0.2000, 0.2000, 0.2000, 0.2000, 0.2000])
Num elves:  tensor([0, 1, 2, 3, 4])
Rocks: tensor([ 0,  4,  8, 12, 16]), Logs: tensor([ 0,  6, 12, 18, 24])
Rocks obs: 4, Logs obs: 6
prior: tensor([0.2000, 0.2000, 0.2000, 0.2000, 0.2000])
Num elves:  tensor([0, 1, 2, 3, 4])
Rocks: tensor([ 0,  4,  8, 12, 16]), Logs: tensor([ 0,  6, 12, 18, 24])
Rocks obs: 4, Logs obs: 6

Traceback (most recent call last):
  File "/Users/jmugan/Dropbox/code/python_examples/jwm_pyro/elves.py", line 75, in <module>
    mcmc.summary(prob=.5)
  File "/Users/jmugan/anaconda3/lib/python3.7/site-packages/pyro/infer/mcmc/api.py", line 485, in summary
    print_summary(self._samples, prob=prob)
  File "/Users/jmugan/anaconda3/lib/python3.7/site-packages/pyro/infer/mcmc/util.py", line 522, in print_summary
    max_len = max(max(map(lambda x: len(x), row_names.values())), 10)
ValueError: max() arg is an empty sequence

Process finished with exit code 1
```

**Comment by fehiepsi** [comment]
Because your `conditioned_model` does not have any continuous **latent** variable, MCMC will collect nothing for you. The ValueError is indeed a bug: we should print an empty summary, rather than triggering an error.

**Comment by jmugan** [comment]
Thanks. I'll have to think about how all this works. I'll leave it open due to the ValueError. Thanks again.

**Comment by fehiepsi** [comment]
In Pyro MCMC, we marginalize the discrete latent variable `num_elves`. After that, there is no latent variable (two variables `rocks_observed` and `logs_observed` are observed after you conditioned on the data). If you only condition on `rocks_observed`
(i.e. `data = {"rocks_observed": torch.tensor(4)}`), then MCMC will collect `logs_observed` samples. I think your model is a nice example to illustrate the difference between using discrete vs continuous latent variables in Pyro. :)
