### ISSUE TITLE
How to run CEVAE model on GPU?

### ISSUE THREAD

**Issue by WeilinChen507** [pyro-ppl/pyro#2885]
### Issue Description
 Hello, I find the pyro implementation of CEVAE is so good. But I want it be able to run on GPU to speed up, and then it returns a RuntimeError as follows:

```
INFO     Training with 10 minibatches per epoch
Traceback (most recent call last):
  File "CEVAE_pyro.py", line 98, in <module>
    main(args)
  File "CEVAE_pyro.py", line 66, in main
    weight_decay=args.weight_decay)
  File "/data1/cwl/anaconda/anaconda3/envs/ltce/lib/python3.7/site-packages/pyro/contrib/cevae/__init__.py", line 545, in fit
    loss = svi.step(x, t, y, size=len(dataset)) / len(dataset)
  File "/data1/cwl/anaconda/anaconda3/envs/ltce/lib/python3.7/site-packages/pyro/infer/svi.py", line 128, in step
    loss = self.loss_and_grads(self.model, self.guide, *args, **kwargs)
  File "/data1/cwl/anaconda/anaconda3/envs/ltce/lib/python3.7/site-packages/pyro/infer/trace_elbo.py", line 131, in loss_and_grads
    for model_trace, guide_trace in self._get_traces(model, guide, args, kwargs):
  File "/data1/cwl/anaconda/anaconda3/envs/ltce/lib/python3.7/site-packages/pyro/infer/elbo.py", line 170, in _get_traces
    yield self._get_trace(model, guide, args, kwargs)
  File "/data1/cwl/anaconda/anaconda3/envs/ltce/lib/python3.7/site-packages/pyro/infer/trace_elbo.py", line 58, in _get_trace
    "flat", self.max_plate_nesting, model, guide, args, kwargs)
  File "/data1/cwl/anaconda/anaconda3/envs/ltce/lib/python3.7/site-packages/pyro/infer/enum.py", line 55, in get_importance_trace
    model_trace.compute_log_prob()
  File "/data1/cwl/anaconda/anaconda3/envs/ltce/lib/python3.7/site-packages/pyro/poutine/trace_struct.py", line 216, in compute_log_prob
    log_p = site["fn"].log_prob(site["value"], *site["args"], **site["kwargs"])
  File "/data1/cwl/anaconda/anaconda3/envs/ltce/lib/python3.7/site-packages/torch/distributions/independent.py", line 91, in log_prob
    log_prob = self.base_dist.log_prob(value)
  File "/data1/cwl/anaconda/anaconda3/envs/ltce/lib/python3.7/site-packages/torch/distributions/normal.py", line 77, in log_prob
    return -((value - self.loc) ** 2) / (2 * var) - log_scale - math.log(math.sqrt(2 * math.pi))
RuntimeError: Expected all tensors to be on the same device, but found at least two de
```

### Environment
 - Linux， cuda 10.2
 - PyTorch version : 1.8.1
 - Pyro version:  1.6.0

### Code Snippet
  I modified the example codes to let CEVAE run on GPU as following (put trained data and model into GPU):
```
    x_train, t_train, y_train = x_train.cuda(), t_train.cuda(), y_train.cuda()
    cevae = CEVAE(feature_dim=args.feature_dim,
                  latent_dim=args.latent_dim,
                  hidden_dim=args.hidden_dim,
                  num_layers=args.num_layers,
                  num_samples=10).cuda()
    cevae.fit(x_train, t_train, y_train,
              num_epochs=args.num_epochs,
              batch_size=args.batch_size,
              learning_rate=args.learning_rate,
              learning_rate_decay=args.learning_rate_decay,
              weight_decay=args.weight_decay)
```
  Example codes are available at https://github.com/pyro-ppl/pyro/blob/dev/examples/contrib/cevae/synthetic.py.
  I am wondering if I incorrectly modified the example codes.

  Thanks for your careful concern.

**Comment by WeilinChen507** [comment]
I have solved the problem by using 
```
     torch.set_default_tensor_type('torch.cuda.FloatTensor')
```
instead of using 
```
    torch.set_default_dtype(torch.float)
```

I guess that the first one lets the tensors of bottom implementation be created on GPU.
