### ISSUE TITLE
[bug] JitTrace_ELBO fails with AutoNormalizingFlow 

### ISSUE THREAD

**Issue by rafaol** [pyro-ppl/pyro#3132]
### Issue Description
Hi all, I'm having issues trying to use normalizing flows with JIT and Pyro's SVI. Code runs fine if I use the standard `Trace_ELBO` (or even `TraceEnum_ELBO` in models with discrete variables), but it fails if I replace the ELBO by its JIT-compiled version. The issue seems to be caused by the use of weak references (`weakref`) when checking unconstrained parameter values. I was wondering if anyone else is having the same issue, and if there's a fix coming up on the horizon.

### Environment
 - OS and python version: Ubuntu 20.04, Python 3.9.7.
 - PyTorch version: 1.12.1
 - Pyro version: 1.8.1+06911dc

### Code Snippet
Here is a minimal example. The following code runs normally if I use `Trace_ELBO` as the loss function for SVI, but fails with `JitTrace_ELBO`.

```python
from functools import partial

import pyro
import pyro.optim
import torch
from pyro import distributions
from pyro.distributions import transforms
from pyro.infer import SVI, JitTrace_ELBO
from pyro.infer.autoguide import AutoNormalizingFlow
from tqdm import trange


def test_model(y):
    m = pyro.sample("m", distributions.MultivariateNormal(torch.zeros(2), torch.eye(2)))
    n = y.shape[0]
    with pyro.plate("observations_plate", n):
        r = pyro.sample("y", distributions.MultivariateNormal(m, 0.01*torch.eye(2)), obs=y)
    return r


if __name__ == "__main__":
    pyro.set_rng_seed(0)

    pyro.clear_param_store()

    transform = partial(transforms.iterated, 10, transforms.block_autoregressive)
    guide = AutoNormalizingFlow(test_model, transform)

    svi = SVI(test_model, guide, pyro.optim.Adam(dict(lr=5e-3)), loss=JitTrace_ELBO())

    n_steps = 1000
    t_iter = trange(n_steps)
    n_data = 100

    test_y = torch.randn(n_data, 2)

    for t in t_iter:
        loss = svi.step(test_y)
        t_iter.set_postfix(loss=loss)
```

#### Console output
```shell
  0%|          | 0/1000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/rafael/opt/anaconda3/envs/latest_torch/lib/python3.9/site-packages/pyro/infer/svi.py", line 145, in step
    loss = self.loss_and_grads(self.model, self.guide, *args, **kwargs)
  File "/home/rafael/opt/anaconda3/envs/latest_torch/lib/python3.9/site-packages/pyro/infer/trace_elbo.py", line 250, in loss_and_grads
    loss, surrogate_loss = self.loss_and_surrogate_loss(
  File "/home/rafael/opt/anaconda3/envs/latest_torch/lib/python3.9/site-packages/pyro/infer/trace_elbo.py", line 239, in loss_and_surrogate_loss
    return self._loss_and_surrogate_loss(*args, **kwargs)
  File "/home/rafael/opt/anaconda3/envs/latest_torch/lib/python3.9/site-packages/pyro/ops/jit.py", line 107, in __call__
    self.compiled[key] = torch.jit.trace(
  File "/home/rafael/opt/anaconda3/envs/latest_torch/lib/python3.9/site-packages/torch/jit/_trace.py", line 795, in trace
    traced = torch._C._create_function_from_trace(
  File "/home/rafael/opt/anaconda3/envs/latest_torch/lib/python3.9/site-packages/pyro/ops/jit.py", line 96, in compiled
    assert constrained_param.unconstrained() is unconstrained_param
AssertionError
```

When I check the runtime environment with the debugger, I see that `constrained_param` holds the same value as `unconstrained_param`,  but `constrained_param.unconstrained()` only holds a `weakref` to the parameter, not the actual value.

#### Values
```
constrained_param:
Parameter containing:
tensor([[-0.0586,  0.0000],
        [ 0.8077,  0.0000],
        [ 0.2949,  0.0000],
        [ 0.0231,  0.0000],
        [-0.7076,  0.0000],
        [ 0.4045,  0.0000],
        [-0.5816,  0.0000],
        [-0.2318,  0.0000],
        [-0.2599, -0.1147],
        [ 0.0085,  0.6389],
        [ 0.0967,  0.6938],
        [ 0.4738, -0.4897],
        [ 0.3474, -0.5476],
        [-0.3283,  0.2278],
        [ 0.2558,  0.5811],
        [-0.2494,  0.0012]], requires_grad=True)
```

`constrained_param.unconstrained = <weakref at 0x7ffa603c4e50; to 'Parameter' at 0x7ffa6041a090>`

```
unconstrained_param:
tensor([[-0.0586,  0.0000],
        [ 0.8077,  0.0000],
        [ 0.2949,  0.0000],
        [ 0.0231,  0.0000],
        [-0.7076,  0.0000],
        [ 0.4045,  0.0000],
        [-0.5816,  0.0000],
        [-0.2318,  0.0000],
        [-0.2599, -0.1147],
        [ 0.0085,  0.6389],
        [ 0.0967,  0.6938],
        [ 0.4738, -0.4897],
        [ 0.3474, -0.5476],
        [-0.3283,  0.2278],
        [ 0.2558,  0.5811],
        [-0.2494,  0.0012]], grad_fn=<ViewBackward0>)
```

**Comment by fritzo** [comment]
Hi @rafaol, tl;dr don't use the jit, it isn't useful.

I have found that `JitTrace_ELBO` only works on very simple models, and provides little or no speed improvement.  I believe this is because the PyTorch team's goals are more to execute models outside of a Python runtime, in contrast to the JAX team's goals which are more performance oriented.  Historically, torch.jit.trace used to slightly speed up some models, but the jit has gradually grown slower so it is no longer useful in Pyro.  I've also found that the torch.jit changes so often across PyTorch releases that I can't rely on my jitted models remaining jittable across minor PyTorch releases.

**Comment by rafaol** [comment]
Thanks @fritzo ! I was actually planning to use JIT on a larger and more complex model (a random effects/hierarchical), which had a significant (10x) speed up in SVI when I tried JIT with a simpler guide (`AutoMultivariateNormal` and `AutoLaplaceApproximation`). I wish I could get the same kind of speed ups with normalizing flows, since they're way more flexible and expressive, but I'll have a look at other options within Pyro.
