### ISSUE TITLE
Error when installing Pyro from source with `make install`

### ISSUE THREAD

**Issue by ordabayevy** [pyro-ppl/pyro#3190]
I get this error when trying to install from source, seems like numpy dependency is missing:
<details>

```
Building wheels for collected packages: visdom, lap, wget
  Building wheel for visdom (setup.py) ... done
  Created wheel for visdom: filename=visdom-0.2.1-py3-none-any.whl size=1407915 sha256=6113b8ed9a4ba5496def8078dc2e0f1e785fc25aa44d6d37609f0887d35c6e9b
  Stored in directory: /Users/yordabay/Library/Caches/pip/wheels/e7/d3/20/190ef652243c03b235306cad864d0a1c22a5c151b689e23cc1
  Building wheel for lap (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      Partial import of lap during the build process.
      Traceback (most recent call last):
        File "/private/var/folders/jw/c8cldqk95mn6nyt_3yj73fnh0000gq/T/pip-install-f4bfovml/lap_bb7260edc2dd43f7adfe874e0e942c1a/setup.py", line 127, in get_numpy_status
          import numpy
      ModuleNotFoundError: No module named 'numpy'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/jw/c8cldqk95mn6nyt_3yj73fnh0000gq/T/pip-install-f4bfovml/lap_bb7260edc2dd43f7adfe874e0e942c1a/setup.py", line 236, in <module>
          setup_package()
        File "/private/var/folders/jw/c8cldqk95mn6nyt_3yj73fnh0000gq/T/pip-install-f4bfovml/lap_bb7260edc2dd43f7adfe874e0e942c1a/setup.py", line 220, in setup_package
          raise ImportError('lap requires numpy, '
      ImportError: lap requires numpy, please "pip install numpy".
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lap
  Running setup.py clean for lap
  Building wheel for wget (setup.py) ... done
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9656 sha256=a8dc2b313ae4ff25d083ef9c491e20a026b9efb695014d812fedb099597d0d39
  Stored in directory: /Users/yordabay/Library/Caches/pip/wheels/bd/a8/c3/3cf2c14a1837a4e04bd98631724e81f33f462d86a1d895fae0
Successfully built visdom wget
Failed to build lap
Installing collected packages: yapf, wget, webencodings, wcwidth, snowballstemmer, Send2Trash, pytz, pyro-api, py-cpuinfo, pure-eval, ptyprocess, pickleshare, ninja, mistune, lap, ipython-genutils, fastjsonschema, executing, backcall, appnope, zipp, widgetsnbextension, websocket-client, webcolors, urllib3, uri-template, typing-extensions, traitlets, tqdm, tornado, tomli, tinycss2, threadpoolctl, sphinxcontrib-serializinghtml, sphinxcontrib-qthelp, sphinxcontrib-jsmath, sphinxcontrib-htmlhelp, sphinxcontrib-devhelp, sphinxcontrib-applehelp, soupsieve, sniffio, six, rfc3986-validator, pyzmq, pyyaml, python-json-logger, pyrsistent, pyparsing, pypandoc, Pygments, pyflakes, pycparser, pycodestyle, psutil, prompt-toolkit, prometheus-client, prettytable, pluggy, platformdirs, pkgutil-resolve-name, pillow, pexpect, pathspec, parso, pandocfilters, packaging, numpy, networkx, nest-asyncio, mypy-extensions, mccabe, MarkupSafe, kiwisolver, jupyterlab-widgets, jupyterlab-pygments, jsonpointer, joblib, isort, iniconfig, imagesize, idna, graphviz, fqdn, fonttools, execnet, exceptiongroup, docutils, defusedxml, decorator, debugpy, cycler, coverage, click, charset-normalizer, babel, attrs, alabaster, torch, terminado, snakeviz, scipy, rfc3339-validator, requests, qtpy, python-dateutil, pytest, opt_einsum, mypy, matplotlib-inline, jupyter-core, jsonpatch, jinja2, jedi, importlib-resources, importlib-metadata, flake8, contourpy, comm, cffi, bleach, black, beautifulsoup4, asttokens, anyio, visdom, torchvision, stack-data, sphinx, scikit-learn, pytest-xdist, pytest-benchmark, pyro-ppl, pandas, matplotlib, jupyter-server-terminals, jupyter-client, jsonschema, arrow, argon2-cffi-bindings, sphinxcontrib-jquery, seaborn, nbformat, isoduration, ipython, argon2-cffi, sphinx_rtd_theme, nbstripout, nbclient, ipykernel, qtconsole, nbval, nbconvert, jupyter-events, jupyter-console, ipywidgets, nbsphinx, jupyter-server, notebook-shim, nbclassic, notebook, jupyter
  Running setup.py install for lap ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for lap did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      Partial import of lap during the build process.
      Traceback (most recent call last):
        File "/private/var/folders/jw/c8cldqk95mn6nyt_3yj73fnh0000gq/T/pip-install-f4bfovml/lap_bb7260edc2dd43f7adfe874e0e942c1a/setup.py", line 127, in get_numpy_status
          import numpy
      ModuleNotFoundError: No module named 'numpy'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/jw/c8cldqk95mn6nyt_3yj73fnh0000gq/T/pip-install-f4bfovml/lap_bb7260edc2dd43f7adfe874e0e942c1a/setup.py", line 236, in <module>
          setup_package()
        File "/private/var/folders/jw/c8cldqk95mn6nyt_3yj73fnh0000gq/T/pip-install-f4bfovml/lap_bb7260edc2dd43f7adfe874e0e942c1a/setup.py", line 220, in setup_package
          raise ImportError('lap requires numpy, '
      ImportError: lap requires numpy, please "pip install numpy".
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> lap

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
make: *** [install] Error 1
```

</details>

**Comment by fritzo** [comment]
oh yeah I think we may need to remove that `lap` dependency at some point. It's almost never used (speak up if you use it) and there is a gross build issue that will start hurting us due to some distutils backwards incompatibility (upstream drama).

In the meantime I think it's safe to add a numpy dependency; I believe we used to rely on PyTorch's dependency.

**Comment by ordabayevy** [comment]
It looks like that `numpy` is already included in `install_requires`, strange that it says that `numpy` is required.

**Comment by ordabayevy** [comment]
This seems to be resolved by itself since I don't see this error message anymore.
